import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { NextProvider } from "@/redux/NextProvider";
import { ThemeProvider } from "@/shadcn/ui/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DateLancer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextProvider>
      <ThemeProvider
          attribute="class"
            defaultTheme="system"
            enableSystem
      >

        <Navbar />
        {children}
        <Footer/>
      </ThemeProvider>
      </NextProvider>
      </body>
    </html>
  );
}
